FROM python:3.11-slim

RUN pip install --no-cache-dir mlflow

RUN mkdir -p /mlflow/mlruns

EXPOSE 5000

CMD ["mlflow", "server", "--backend-store-uri", "sqlite:////mlflow/mlflow.db", "--default-artifact-root", "file:///mlflow/mlruns", "--host", "0.0.0.0", "--port", "5000"]

