apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
      - name: mlflow
        image: creditriskacrguetch.azurecr.io/mlflow:latest
        ports:
        - containerPort: 5000

        resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"

        volumeMounts:
        - name: mlflow-data
          mountPath: /mlflow

      volumes:
      - name: mlflow-data
        emptyDir: {}
