apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "051b26c1-8890-4a8e-affc-6695047ee2c3"
    keyvaultName: kv-mlops-creditrisk
    tenantId: 6cd1f8d1-a460-425b-b22b-ffbece392cf0
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
